# tools/admin_scripts/seed_exercises_expansion.py
"""
Seed 100 nuovi esercizi principali — colma gap muscolari e arricchisce pattern.

Aree coperte:
  - Polpacci (10), Adduttori (8), Trapezi (6), Carry/Grip (6)
  - Rotation/Anti-rotation (8), Pull_v avanzati (8), Push_h avanzati (8)
  - Core avanzato (8), Hinge varianti (6), Isolation mancanti (10)
  - Cardio/Conditioning (8), Bodyweight avanzato (8), Kettlebell (6)

Uso:
  python -m tools.admin_scripts.seed_exercises_expansion                          # crm.db
  DATABASE_URL=sqlite:///data/crm_dev.db python -m tools.admin_scripts.seed_exercises_expansion  # dev
"""

import json
import os
import sqlite3
from datetime import datetime

DB_PATH = os.environ.get("DATABASE_URL", "sqlite:///data/crm.db").replace("sqlite:///", "")

EXERCISES = [
    # ═══════════════════════════════════════════════════════════
    # POLPACCI — 10 esercizi (gap CRITICO: da 3 a 13)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Calf Raise in Piedi al Bilanciere",
        "nome_en": "Standing Barbell Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise in Piedi ai Manubri",
        "nome_en": "Standing Dumbbell Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise alla Macchina in Piedi",
        "nome_en": "Standing Machine Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise Seduto alla Macchina",
        "nome_en": "Seated Machine Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Donkey Calf Raise",
        "nome_en": "Donkey Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "machine",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise Singolo su Rialzo",
        "nome_en": "Single-Leg Calf Raise on Step",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Press alla Leg Press",
        "nome_en": "Calf Press on Leg Press",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise al Multipower",
        "nome_en": "Smith Machine Calf Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Tibialis Raise",
        "nome_en": "Tibialis Raise",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Calf Raise Esplosivo a Corpo Libero",
        "nome_en": "Explosive Bodyweight Calf Raise",
        "categoria": "bodyweight",
        "pattern_movimento": "squat",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },

    # ═══════════════════════════════════════════════════════════
    # ADDUTTORI — 8 esercizi (gap CRITICO: da 0 a 8)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Adductor Machine",
        "nome_en": "Hip Adduction Machine",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Copenhagen Plank",
        "nome_en": "Copenhagen Plank",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["adductors", "core"],
        "muscoli_secondari": ["glutes", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 36,
    },
    {
        "nome": "Adduzione con Elastico",
        "nome_en": "Band Hip Adduction",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Sumo Squat con Manubrio",
        "nome_en": "Dumbbell Sumo Squat",
        "categoria": "compound",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "adductors", "glutes"],
        "muscoli_secondari": ["hamstrings", "core"],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 48,
    },
    {
        "nome": "Cossack Squat",
        "nome_en": "Cossack Squat",
        "categoria": "bodyweight",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors", "quadriceps", "glutes"],
        "muscoli_secondari": ["hamstrings", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Adduzione al Cavo Basso",
        "nome_en": "Cable Hip Adduction",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Ball Squeeze Isometrico",
        "nome_en": "Isometric Ball Squeeze",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Adduzione Laterale a Terra",
        "nome_en": "Side-Lying Hip Adduction",
        "categoria": "isolation",
        "pattern_movimento": "squat",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },

    # ═══════════════════════════════════════════════════════════
    # TRAPEZI — 6 esercizi (da 7 secondari a 13 con dedicati)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Scrollate Bilanciere",
        "nome_en": "Barbell Shrug",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders", "forearms"],
        "attrezzatura": "barbell",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Scrollate Manubri",
        "nome_en": "Dumbbell Shrug",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders", "forearms"],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Scrollate alla Macchina",
        "nome_en": "Machine Shrug",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Scrollate Trap Bar",
        "nome_en": "Trap Bar Shrug",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps", "forearms"],
        "muscoli_secondari": ["shoulders", "back"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Scrollate Dietro la Schiena al Multipower",
        "nome_en": "Behind-Back Smith Machine Shrug",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "machine",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Scrollate ai Cavi",
        "nome_en": "Cable Shrug",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders", "forearms"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },

    # ═══════════════════════════════════════════════════════════
    # CARRY / GRIP — 6 esercizi (da 6 a 12)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Farmer Walk con Manubri",
        "nome_en": "Dumbbell Farmer Walk",
        "categoria": "compound",
        "pattern_movimento": "carry",
        "muscoli_primari": ["forearms", "traps", "core"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Suitcase Carry",
        "nome_en": "Suitcase Carry",
        "categoria": "compound",
        "pattern_movimento": "carry",
        "muscoli_primari": ["core", "forearms", "traps"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Waiter Walk",
        "nome_en": "Waiter Walk",
        "categoria": "compound",
        "pattern_movimento": "carry",
        "muscoli_primari": ["shoulders", "core", "traps"],
        "muscoli_secondari": ["forearms", "triceps"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Dead Hang",
        "nome_en": "Dead Hang",
        "categoria": "bodyweight",
        "pattern_movimento": "carry",
        "muscoli_primari": ["forearms", "lats", "shoulders"],
        "muscoli_secondari": ["biceps", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Farmer Walk con Kettlebell",
        "nome_en": "Kettlebell Farmer Walk",
        "categoria": "compound",
        "pattern_movimento": "carry",
        "muscoli_primari": ["forearms", "traps", "core"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "kettlebell",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Bear Hug Carry",
        "nome_en": "Bear Hug Carry",
        "categoria": "compound",
        "pattern_movimento": "carry",
        "muscoli_primari": ["core", "biceps", "forearms"],
        "muscoli_secondari": ["shoulders", "chest", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },

    # ═══════════════════════════════════════════════════════════
    # ROTATION / ANTI-ROTATION — 8 esercizi (da 7 a 15)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Pallof Press al Cavo",
        "nome_en": "Cable Pallof Press",
        "categoria": "isolation",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Pallof Press con Elastico",
        "nome_en": "Band Pallof Press",
        "categoria": "isolation",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Woodchop al Cavo Alto-Basso",
        "nome_en": "High-to-Low Cable Woodchop",
        "categoria": "compound",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core", "shoulders"],
        "muscoli_secondari": ["glutes", "back"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Woodchop al Cavo Basso-Alto",
        "nome_en": "Low-to-High Cable Woodchop",
        "categoria": "compound",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core", "shoulders"],
        "muscoli_secondari": ["glutes", "back"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Landmine Rotation",
        "nome_en": "Landmine Rotation",
        "categoria": "compound",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core", "shoulders"],
        "muscoli_secondari": ["glutes", "back", "chest"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Russian Twist con Peso",
        "nome_en": "Weighted Russian Twist",
        "categoria": "isolation",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Rotazione al Cavo in Piedi",
        "nome_en": "Standing Cable Rotation",
        "categoria": "isolation",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Med Ball Rotational Throw",
        "nome_en": "Medicine Ball Rotational Throw",
        "categoria": "compound",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core", "shoulders", "chest"],
        "muscoli_secondari": ["glutes", "back"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },

    # ═══════════════════════════════════════════════════════════
    # PULL_V AVANZATI — 8 esercizi (da 15 a 23)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Trazioni Zavorrate",
        "nome_en": "Weighted Pull-Up",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "biceps", "back"],
        "muscoli_secondari": ["forearms", "core", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Muscle-Up alla Sbarra",
        "nome_en": "Bar Muscle-Up",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "chest", "triceps"],
        "muscoli_secondari": ["biceps", "core", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Lat Prayer al Cavo",
        "nome_en": "Cable Lat Prayer",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats"],
        "muscoli_secondari": ["core", "triceps"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Lat Pulldown Presa Stretta",
        "nome_en": "Close-Grip Lat Pulldown",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "biceps"],
        "muscoli_secondari": ["back", "forearms"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Pulldown a Braccia Tese",
        "nome_en": "Straight-Arm Lat Pulldown",
        "categoria": "isolation",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats"],
        "muscoli_secondari": ["triceps", "core"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Trazioni Negative",
        "nome_en": "Negative Pull-Up",
        "categoria": "bodyweight",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "biceps", "back"],
        "muscoli_secondari": ["forearms", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Chin-Up Presa Supina",
        "nome_en": "Chin-Up",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["biceps", "lats", "back"],
        "muscoli_secondari": ["forearms", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Trazioni agli Anelli",
        "nome_en": "Ring Pull-Up",
        "categoria": "compound",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "biceps", "back"],
        "muscoli_secondari": ["forearms", "core", "shoulders"],
        "attrezzatura": "trx",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },

    # ═══════════════════════════════════════════════════════════
    # PUSH_H AVANZATI — 8 esercizi (da 21 a 29)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Floor Press Manubri",
        "nome_en": "Dumbbell Floor Press",
        "categoria": "compound",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Floor Press Bilanciere",
        "nome_en": "Barbell Floor Press",
        "categoria": "compound",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Svend Press",
        "nome_en": "Svend Press",
        "categoria": "isolation",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest"],
        "muscoli_secondari": ["shoulders", "triceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Panca Declinata Bilanciere",
        "nome_en": "Decline Barbell Bench Press",
        "categoria": "compound",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Panca Declinata Manubri",
        "nome_en": "Decline Dumbbell Press",
        "categoria": "compound",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Squeeze Press Manubri",
        "nome_en": "Dumbbell Squeeze Press",
        "categoria": "compound",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Push-Up con Deficit",
        "nome_en": "Deficit Push-Up",
        "categoria": "bodyweight",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps", "shoulders"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Archer Push-Up",
        "nome_en": "Archer Push-Up",
        "categoria": "bodyweight",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps", "shoulders"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 36,
    },

    # ═══════════════════════════════════════════════════════════
    # CORE AVANZATO — 8 esercizi (da 14 a 22)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Ab Wheel Rollout",
        "nome_en": "Ab Wheel Rollout",
        "categoria": "isolation",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders", "lats"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Dragon Flag",
        "nome_en": "Dragon Flag",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["lats", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Hollow Body Hold",
        "nome_en": "Hollow Body Hold",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["quadriceps", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "L-Sit",
        "nome_en": "L-Sit Hold",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core", "quadriceps"],
        "muscoli_secondari": ["shoulders", "triceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 36,
    },
    {
        "nome": "Hanging Leg Raise",
        "nome_en": "Hanging Leg Raise",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["forearms", "quadriceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Toes to Bar",
        "nome_en": "Toes to Bar",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["forearms", "lats", "quadriceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 36,
    },
    {
        "nome": "Dead Bug con Peso",
        "nome_en": "Weighted Dead Bug",
        "categoria": "isolation",
        "pattern_movimento": "core",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Stir the Pot",
        "nome_en": "Stir the Pot",
        "categoria": "bodyweight",
        "pattern_movimento": "core",
        "muscoli_primari": ["core", "shoulders"],
        "muscoli_secondari": ["glutes", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },

    # ═══════════════════════════════════════════════════════════
    # HINGE VARIANTI — 6 esercizi (da 26 a 32)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Jefferson Curl",
        "nome_en": "Jefferson Curl",
        "categoria": "isolation",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["hamstrings", "back"],
        "muscoli_secondari": ["glutes", "calves"],
        "attrezzatura": "dumbbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Nordic Hamstring Curl",
        "nome_en": "Nordic Hamstring Curl",
        "categoria": "bodyweight",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["hamstrings"],
        "muscoli_secondari": ["glutes", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Reverse Hyperextension",
        "nome_en": "Reverse Hyperextension",
        "categoria": "isolation",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings"],
        "muscoli_secondari": ["back"],
        "attrezzatura": "machine",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Pull Through al Cavo",
        "nome_en": "Cable Pull Through",
        "categoria": "compound",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings"],
        "muscoli_secondari": ["back", "core"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 36,
    },
    {
        "nome": "Kettlebell Swing",
        "nome_en": "Kettlebell Swing",
        "categoria": "compound",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings", "core"],
        "muscoli_secondari": ["shoulders", "back", "forearms"],
        "attrezzatura": "kettlebell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Sumo Deadlift",
        "nome_en": "Sumo Deadlift",
        "categoria": "compound",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings", "quadriceps"],
        "muscoli_secondari": ["back", "adductors", "core", "forearms"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },

    # ═══════════════════════════════════════════════════════════
    # ISOLATION MANCANTI — 10 esercizi
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Concentration Curl",
        "nome_en": "Concentration Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["biceps"],
        "muscoli_secondari": ["forearms"],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Preacher Curl alla Panca Scott",
        "nome_en": "Preacher Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["biceps"],
        "muscoli_secondari": ["forearms"],
        "attrezzatura": "barbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Cable Fly Basso (Incline)",
        "nome_en": "Low Cable Fly",
        "categoria": "isolation",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Cable Fly Alto (Decline)",
        "nome_en": "High Cable Fly",
        "categoria": "isolation",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "French Press al Cavo",
        "nome_en": "Cable Overhead Tricep Extension",
        "categoria": "isolation",
        "pattern_movimento": "push_v",
        "muscoli_primari": ["triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "cable",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Skull Crusher",
        "nome_en": "Skull Crusher",
        "categoria": "isolation",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["triceps"],
        "muscoli_secondari": ["shoulders", "chest"],
        "attrezzatura": "barbell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Curl Inverso Bilanciere",
        "nome_en": "Reverse Barbell Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["forearms", "biceps"],
        "muscoli_secondari": [],
        "attrezzatura": "barbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Wrist Curl con Manubrio",
        "nome_en": "Dumbbell Wrist Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["forearms"],
        "muscoli_secondari": [],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Reverse Wrist Curl",
        "nome_en": "Reverse Wrist Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["forearms"],
        "muscoli_secondari": [],
        "attrezzatura": "dumbbell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Spider Curl al Cavo",
        "nome_en": "Cable Spider Curl",
        "categoria": "isolation",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["biceps"],
        "muscoli_secondari": ["forearms"],
        "attrezzatura": "cable",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },

    # ═══════════════════════════════════════════════════════════
    # CARDIO / CONDITIONING — 8 esercizi (da 9 a 17)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Battle Rope",
        "nome_en": "Battle Rope Waves",
        "categoria": "cardio",
        "pattern_movimento": "push_v",
        "muscoli_primari": ["shoulders", "core"],
        "muscoli_secondari": ["forearms", "back", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 24,
    },
    {
        "nome": "Sled Push",
        "nome_en": "Sled Push",
        "categoria": "cardio",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "glutes", "core"],
        "muscoli_secondari": ["calves", "shoulders", "chest"],
        "attrezzatura": "machine",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Box Jump",
        "nome_en": "Box Jump",
        "categoria": "cardio",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "glutes", "calves"],
        "muscoli_secondari": ["core", "hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Rowing Machine",
        "nome_en": "Rowing Machine",
        "categoria": "cardio",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["back", "quadriceps", "core"],
        "muscoli_secondari": ["biceps", "glutes", "hamstrings"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Assault Bike",
        "nome_en": "Assault Bike / Air Bike",
        "categoria": "cardio",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "shoulders", "core"],
        "muscoli_secondari": ["glutes", "hamstrings", "biceps"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Burpee con Salto",
        "nome_en": "Burpee with Jump",
        "categoria": "cardio",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "chest", "core"],
        "muscoli_secondari": ["shoulders", "triceps", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Bear Crawl",
        "nome_en": "Bear Crawl",
        "categoria": "cardio",
        "pattern_movimento": "core",
        "muscoli_primari": ["core", "shoulders", "quadriceps"],
        "muscoli_secondari": ["triceps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
    {
        "nome": "Shuttle Run",
        "nome_en": "Shuttle Run / Suicide Sprints",
        "categoria": "cardio",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "hamstrings", "calves"],
        "muscoli_secondari": ["glutes", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },

    # ═══════════════════════════════════════════════════════════
    # BODYWEIGHT AVANZATO — 8 esercizi (da 32 a 40)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Pistol Squat",
        "nome_en": "Pistol Squat",
        "categoria": "bodyweight",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "glutes"],
        "muscoli_secondari": ["core", "hamstrings", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Handstand Push-Up",
        "nome_en": "Handstand Push-Up",
        "categoria": "bodyweight",
        "pattern_movimento": "push_v",
        "muscoli_primari": ["shoulders", "triceps"],
        "muscoli_secondari": ["core", "traps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Dip agli Anelli",
        "nome_en": "Ring Dip",
        "categoria": "bodyweight",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["chest", "triceps", "shoulders"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "trx",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Planche Lean",
        "nome_en": "Planche Lean",
        "categoria": "bodyweight",
        "pattern_movimento": "push_h",
        "muscoli_primari": ["shoulders", "chest", "core"],
        "muscoli_secondari": ["triceps", "forearms"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Front Lever Progressione",
        "nome_en": "Front Lever Progression",
        "categoria": "bodyweight",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["lats", "core", "back"],
        "muscoli_secondari": ["biceps", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Back Lever Progressione",
        "nome_en": "Back Lever Progression",
        "categoria": "bodyweight",
        "pattern_movimento": "pull_h",
        "muscoli_primari": ["shoulders", "back", "biceps"],
        "muscoli_secondari": ["core", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Skin the Cat",
        "nome_en": "Skin the Cat",
        "categoria": "bodyweight",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["shoulders", "lats", "core"],
        "muscoli_secondari": ["biceps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Muscle-Up agli Anelli",
        "nome_en": "Ring Muscle-Up",
        "categoria": "bodyweight",
        "pattern_movimento": "pull_v",
        "muscoli_primari": ["lats", "chest", "triceps"],
        "muscoli_secondari": ["biceps", "core", "shoulders"],
        "attrezzatura": "trx",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },

    # ═══════════════════════════════════════════════════════════
    # KETTLEBELL SPECIFICI — 6 esercizi (da 11 a 17)
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Turkish Get-Up",
        "nome_en": "Turkish Get-Up",
        "categoria": "compound",
        "pattern_movimento": "core",
        "muscoli_primari": ["core", "shoulders", "glutes"],
        "muscoli_secondari": ["quadriceps", "hamstrings", "triceps"],
        "attrezzatura": "kettlebell",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Kettlebell Clean",
        "nome_en": "Kettlebell Clean",
        "categoria": "compound",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings", "shoulders"],
        "muscoli_secondari": ["core", "forearms", "back"],
        "attrezzatura": "kettlebell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Kettlebell Snatch",
        "nome_en": "Kettlebell Snatch",
        "categoria": "compound",
        "pattern_movimento": "hinge",
        "muscoli_primari": ["glutes", "hamstrings", "shoulders"],
        "muscoli_secondari": ["core", "forearms", "back", "traps"],
        "attrezzatura": "kettlebell",
        "difficolta": "advanced",
        "ore_recupero": 48,
    },
    {
        "nome": "Kettlebell Windmill",
        "nome_en": "Kettlebell Windmill",
        "categoria": "compound",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["core", "shoulders", "hamstrings"],
        "muscoli_secondari": ["glutes", "back"],
        "attrezzatura": "kettlebell",
        "difficolta": "intermediate",
        "ore_recupero": 36,
    },
    {
        "nome": "Double Kettlebell Front Squat",
        "nome_en": "Double Kettlebell Front Squat",
        "categoria": "compound",
        "pattern_movimento": "squat",
        "muscoli_primari": ["quadriceps", "glutes", "core"],
        "muscoli_secondari": ["hamstrings", "shoulders"],
        "attrezzatura": "kettlebell",
        "difficolta": "intermediate",
        "ore_recupero": 48,
    },
    {
        "nome": "Kettlebell Halo",
        "nome_en": "Kettlebell Halo",
        "categoria": "isolation",
        "pattern_movimento": "rotation",
        "muscoli_primari": ["shoulders", "core"],
        "muscoli_secondari": ["traps", "forearms"],
        "attrezzatura": "kettlebell",
        "difficolta": "beginner",
        "ore_recupero": 24,
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()

    # Nomi gia' presenti
    cursor.execute("SELECT nome FROM esercizi")
    existing = {row[0] for row in cursor.fetchall()}

    inserted = 0
    skipped = 0

    for ex in EXERCISES:
        if ex["nome"] in existing:
            print(f"  SKIP (esiste gia'): {ex['nome']}")
            skipped += 1
            continue

        cursor.execute(
            """
            INSERT INTO esercizi (
                trainer_id, nome, nome_en, categoria, pattern_movimento,
                force_type, lateral_pattern,
                muscoli_primari, muscoli_secondari,
                attrezzatura, difficolta, ore_recupero,
                descrizione_anatomica,
                is_builtin, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
            """,
            (
                None,  # builtin
                ex["nome"],
                ex["nome_en"],
                ex["categoria"],
                ex["pattern_movimento"],
                ex.get("force_type"),
                ex.get("lateral_pattern"),
                json.dumps(ex["muscoli_primari"]),
                json.dumps(ex["muscoli_secondari"]),
                ex["attrezzatura"],
                ex["difficolta"],
                ex.get("ore_recupero", 48),
                ex.get("descrizione_anatomica", ""),
                now,
            ),
        )
        inserted += 1
        print(f"  + {ex['nome']} ({ex['categoria']}/{ex['pattern_movimento']})")

    conn.commit()

    # Report
    cursor.execute("SELECT COUNT(*) FROM esercizi")
    total = cursor.fetchone()[0]
    cursor.execute("SELECT categoria, COUNT(*) FROM esercizi GROUP BY categoria ORDER BY COUNT(*) DESC")
    by_cat = cursor.fetchall()

    print(f"\n{'='*50}")
    print(f"Inseriti: {inserted} | Saltati: {skipped} | Totale DB: {total}")
    print(f"\nDistribuzione per categoria:")
    for cat, count in by_cat:
        print(f"  {cat}: {count}")

    conn.close()


if __name__ == "__main__":
    main()
