# tools/admin_scripts/seed_complementary_v2.py
"""
Seed 45 nuovi esercizi complementari (15 avviamento + 15 stretching + 15 mobilita).

Completa la copertura muscolare nelle sezioni avviamento/stretching/mobilita.

Uso:
  python -m tools.admin_scripts.seed_complementary_v2                          # crm.db
  DATABASE_URL=sqlite:///data/crm_dev.db python -m tools.admin_scripts.seed_complementary_v2  # dev
"""

import json
import os
import sqlite3
from datetime import datetime

DB_PATH = os.environ.get("DATABASE_URL", "sqlite:///data/crm.db").replace("sqlite:///", "")

EXERCISES = [
    # ═══════════════════════════════════════════════════════════
    # AVVIAMENTO v2 — 15 esercizi (da 11 a 26)
    # Focus: attivazione specifica, band activation, crawl, sport-specific
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Glute Bridge Attivazione",
        "nome_en": "Glute Bridge Activation",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["glutes", "hamstrings"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Clamshell con Elastico",
        "nome_en": "Banded Clamshell",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Band Pull Apart",
        "nome_en": "Band Pull Apart",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders", "back"],
        "muscoli_secondari": ["traps"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Band Walk Laterale",
        "nome_en": "Lateral Band Walk",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["quadriceps", "core"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Bear Crawl Riscaldamento",
        "nome_en": "Warm-Up Bear Crawl",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["core", "shoulders", "quadriceps"],
        "muscoli_secondari": ["triceps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Crab Walk",
        "nome_en": "Crab Walk",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["triceps", "shoulders", "core"],
        "muscoli_secondari": ["glutes", "hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Arm Circles Dinamici",
        "nome_en": "Dynamic Arm Circles",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders"],
        "muscoli_secondari": ["traps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Butt Kicks Corsa",
        "nome_en": "Butt Kicks",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["hamstrings", "calves"],
        "muscoli_secondari": ["quadriceps", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Toy Soldier March",
        "nome_en": "Toy Soldier March",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["hamstrings", "core"],
        "muscoli_secondari": ["quadriceps", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Lateral Shuffle",
        "nome_en": "Lateral Shuffle",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["glutes", "quadriceps", "adductors"],
        "muscoli_secondari": ["calves", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "A-Skip",
        "nome_en": "A-Skip Drill",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["quadriceps", "calves", "core"],
        "muscoli_secondari": ["hamstrings", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Karaoke / Carioca",
        "nome_en": "Carioca Drill",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["adductors", "glutes", "core"],
        "muscoli_secondari": ["calves", "quadriceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Plank Walk-Out",
        "nome_en": "Plank Walk-Out",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["core", "shoulders", "hamstrings"],
        "muscoli_secondari": ["chest", "triceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Scapular Push-Up",
        "nome_en": "Scapular Push-Up",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "shoulders"],
        "muscoli_secondari": ["core", "traps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Cyclette Leggera",
        "nome_en": "Light Stationary Bike",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["quadriceps", "hamstrings", "calves"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "machine",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },

    # ═══════════════════════════════════════════════════════════
    # STRETCHING v2 — 15 esercizi (da 12 a 27)
    # Focus: muscoli mancanti (avambracci, trapezi, polpacci, tibiale, IT band)
    # + varianti PNF e partner
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Stretching Avambracci Flessori",
        "nome_en": "Forearm Flexor Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["forearms"],
        "muscoli_secondari": ["biceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Avambracci Estensori",
        "nome_en": "Forearm Extensor Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["forearms"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Trapezio Superiore",
        "nome_en": "Upper Trap Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Polpaccio al Muro",
        "nome_en": "Wall Calf Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": ["hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Soleo Seduto",
        "nome_en": "Seated Soleus Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching IT Band (Fascia Lata)",
        "nome_en": "IT Band Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["glutes", "quadriceps"],
        "muscoli_secondari": ["adductors"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Bicipite al Muro",
        "nome_en": "Wall Bicep Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["biceps"],
        "muscoli_secondari": ["chest", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Piriforme Supino",
        "nome_en": "Supine Piriformis Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["glutes"],
        "muscoli_secondari": ["hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Gran Dorsale Laterale",
        "nome_en": "Side Lat Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["lats"],
        "muscoli_secondari": ["core", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Adduttori in Piedi",
        "nome_en": "Standing Adductor Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["hamstrings", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Quadrato dei Lombi",
        "nome_en": "QL Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["back", "core"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Child's Pose (Posizione del Bambino)",
        "nome_en": "Child's Pose",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "lats", "shoulders"],
        "muscoli_secondari": ["glutes", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Pettorale alla Porta",
        "nome_en": "Doorway Chest Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["chest"],
        "muscoli_secondari": ["shoulders", "biceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Stretching Femorali con Fascia",
        "nome_en": "Banded Hamstring Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["hamstrings"],
        "muscoli_secondari": ["calves", "glutes"],
        "attrezzatura": "band",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Frog Stretch",
        "nome_en": "Frog Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["adductors", "glutes"],
        "muscoli_secondari": ["hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },

    # ═══════════════════════════════════════════════════════════
    # MOBILITA v2 — 15 esercizi (da 12 a 27)
    # Focus: CARs, flow sequences, mobilita squat/overhead/thoracic
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "CARs Spalla (Rotazioni Controllate)",
        "nome_en": "Shoulder CARs",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["shoulders"],
        "muscoli_secondari": ["traps", "back"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "CARs Anca (Rotazioni Controllate)",
        "nome_en": "Hip CARs",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["core", "hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "CARs Cervicale",
        "nome_en": "Cervical CARs",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Bretzel Stretch",
        "nome_en": "Bretzel Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["core", "chest", "quadriceps"],
        "muscoli_secondari": ["shoulders", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
    },
    {
        "nome": "Jefferson Curl Mobilita",
        "nome_en": "Mobility Jefferson Curl",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["hamstrings", "back"],
        "muscoli_secondari": ["calves", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
    },
    {
        "nome": "Pigeon Pose Dinamico",
        "nome_en": "Dynamic Pigeon Pose",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["hamstrings", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
    },
    {
        "nome": "Mobilita Overhead con Bastone",
        "nome_en": "Overhead Mobility with Dowel",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders", "lats"],
        "muscoli_secondari": ["core", "traps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Squat Mobility Flow",
        "nome_en": "Squat Mobility Flow",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["adductors", "quadriceps", "calves"],
        "muscoli_secondari": ["glutes", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "T-Spine Rotation su Foam Roller",
        "nome_en": "T-Spine Rotation on Foam Roller",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "core"],
        "muscoli_secondari": ["shoulders", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Rocking Hip Flexor Stretch",
        "nome_en": "Rocking Hip Flexor Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["quadriceps", "glutes"],
        "muscoli_secondari": ["core", "hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Wall Slide (Angels)",
        "nome_en": "Wall Slide / Wall Angels",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders", "back"],
        "muscoli_secondari": ["traps", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Quadruped Thoracic Rotation",
        "nome_en": "Quadruped Thoracic Rotation",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["back", "core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Couch Stretch",
        "nome_en": "Couch Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["quadriceps", "glutes"],
        "muscoli_secondari": ["core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
    },
    {
        "nome": "Goblet Squat Hold con Pulsazioni",
        "nome_en": "Goblet Squat Hold with Pulses",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["adductors", "quadriceps", "glutes"],
        "muscoli_secondari": ["core", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
    {
        "nome": "Downward Dog to Cobra Flow",
        "nome_en": "Down Dog to Cobra Flow",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders", "hamstrings", "chest"],
        "muscoli_secondari": ["core", "back", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()

    # Nomi gia' presenti
    cursor.execute("SELECT nome FROM esercizi")
    existing = {row[0] for row in cursor.fetchall()}

    inserted = 0
    skipped = 0

    for ex in EXERCISES:
        if ex["nome"] in existing:
            print(f"  SKIP (esiste gia'): {ex['nome']}")
            skipped += 1
            continue

        cursor.execute(
            """
            INSERT INTO esercizi (
                trainer_id, nome, nome_en, categoria, pattern_movimento,
                force_type, lateral_pattern,
                muscoli_primari, muscoli_secondari,
                attrezzatura, difficolta, ore_recupero,
                descrizione_anatomica,
                is_builtin, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
            """,
            (
                None,  # builtin
                ex["nome"],
                ex["nome_en"],
                ex["categoria"],
                ex["pattern_movimento"],
                ex.get("force_type"),
                ex.get("lateral_pattern"),
                json.dumps(ex["muscoli_primari"]),
                json.dumps(ex["muscoli_secondari"]),
                ex["attrezzatura"],
                ex["difficolta"],
                ex.get("ore_recupero", 12),
                ex.get("descrizione_anatomica", ""),
                now,
            ),
        )
        inserted += 1
        print(f"  + {ex['nome']} ({ex['categoria']}/{ex['pattern_movimento']})")

    conn.commit()

    # Report
    cursor.execute("SELECT COUNT(*) FROM esercizi")
    total = cursor.fetchone()[0]
    cursor.execute("SELECT categoria, COUNT(*) FROM esercizi GROUP BY categoria ORDER BY COUNT(*) DESC")
    by_cat = cursor.fetchall()

    print(f"\n{'='*50}")
    print(f"Inseriti: {inserted} | Saltati: {skipped} | Totale DB: {total}")
    print(f"\nDistribuzione per categoria:")
    for cat, count in by_cat:
        print(f"  {cat}: {count}")

    conn.close()


if __name__ == "__main__":
    main()
