# tools/admin_scripts/seed_complementary_exercises.py
"""
Seed esercizi complementari: avviamento, stretching, mobilita.

Inserisce ~35 esercizi builtin nelle nuove categorie.
Eseguire su entrambi i DB (crm.db + crm_dev.db).

Uso:
  python -m tools.admin_scripts.seed_complementary_exercises          # crm.db (prod)
  DATABASE_URL=sqlite:///data/crm_dev.db python -m tools.admin_scripts.seed_complementary_exercises  # dev
"""

import json
import os
import sqlite3
from datetime import datetime

DB_PATH = os.environ.get("DATABASE_URL", "sqlite:///data/crm.db").replace("sqlite:///", "")

EXERCISES = [
    # ═══════════════════════════════════════════════════════════
    # AVVIAMENTO (warm-up) — 12 esercizi
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Corsa Leggera",
        "nome_en": "Light Jog",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["quadriceps", "hamstrings", "calves"],
        "muscoli_secondari": ["glutes", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Attivazione cardiovascolare a bassa intensita. Coinvolge catena cinetica inferiore con impatto minimo.",
    },
    {
        "nome": "Jumping Jacks",
        "nome_en": "Jumping Jacks",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders", "calves", "quadriceps"],
        "muscoli_secondari": ["core", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Esercizio cardio a corpo libero che attiva tutto il corpo. Abduzione/adduzione arti superiori e inferiori in sincrono.",
    },
    {
        "nome": "Skip Sul Posto",
        "nome_en": "High Knees",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["quadriceps", "core", "calves"],
        "muscoli_secondari": ["hamstrings", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Elevazione alternata delle ginocchia. Attiva flessori dell'anca, quadricipiti e core.",
    },
    {
        "nome": "Calci Indietro",
        "nome_en": "Butt Kicks",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["hamstrings", "calves"],
        "muscoli_secondari": ["quadriceps", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Flessione alternata del ginocchio portando il tallone al gluteo. Attiva femorali e polpacci.",
    },
    {
        "nome": "Cerchi Braccia",
        "nome_en": "Arm Circles",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders"],
        "muscoli_secondari": ["traps", "chest"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Rotazione completa delle braccia a braccia tese. Riscalda cuffia dei rotatori e deltoidi.",
    },
    {
        "nome": "Rotazioni del Tronco",
        "nome_en": "Trunk Rotations",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["core"],
        "muscoli_secondari": ["back", "shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Rotazione del busto a destra e sinistra. Attiva obliqui e mobilizza la colonna toracica.",
    },
    {
        "nome": "Affondi Camminata Bodyweight",
        "nome_en": "Walking Lunges Bodyweight",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["quadriceps", "glutes"],
        "muscoli_secondari": ["hamstrings", "calves", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Affondi in camminata senza carico. Attiva quadricipiti, glutei e migliora equilibrio dinamico.",
    },
    {
        "nome": "Inchworm",
        "nome_en": "Inchworm",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["core", "shoulders", "hamstrings"],
        "muscoli_secondari": ["chest", "triceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Dalla posizione eretta, mani a terra e camminata in avanti fino a plank, poi ritorno. Attiva catena posteriore e spalle.",
    },
    {
        "nome": "Salto alla Corda",
        "nome_en": "Jump Rope",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["calves", "quadriceps", "shoulders"],
        "muscoli_secondari": ["core", "forearms"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Salti continui con corda. Eccellente per attivazione cardiovascolare e coordinazione.",
    },
    {
        "nome": "Mountain Climbers",
        "nome_en": "Mountain Climbers",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["core", "quadriceps", "shoulders"],
        "muscoli_secondari": ["hamstrings", "chest", "triceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Da posizione plank, alternare ginocchia verso il petto. Attivazione intensa core + cardio.",
    },
    {
        "nome": "Squat Bodyweight",
        "nome_en": "Bodyweight Squat",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["quadriceps", "glutes"],
        "muscoli_secondari": ["hamstrings", "core", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Squat senza carico per attivare la catena cinetica inferiore e preparare le articolazioni.",
    },
    {
        "nome": "Ginocchia al Petto Alternato",
        "nome_en": "Alternating Knee Hugs",
        "categoria": "avviamento",
        "pattern_movimento": "warmup",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["glutes", "hamstrings", "core"],
        "muscoli_secondari": ["calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "In piedi, portare alternando il ginocchio al petto. Stretching dinamico glutei e femorali.",
    },

    # ═══════════════════════════════════════════════════════════
    # STRETCHING — 12 esercizi
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Stretching Quadricipiti",
        "nome_en": "Standing Quad Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["quadriceps"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "In piedi, afferrare il piede dietro e tirare il tallone verso il gluteo. Allunga retto femorale e vasto.",
    },
    {
        "nome": "Stretching Femorali",
        "nome_en": "Standing Hamstring Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["hamstrings"],
        "muscoli_secondari": ["calves", "back"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Gamba tesa su rialzo, inclinarsi in avanti dal bacino. Allunga bicipite femorale e semitendinoso.",
    },
    {
        "nome": "Stretching Polpacci",
        "nome_en": "Calf Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Gamba distesa indietro con tallone a terra, inclinare il corpo avanti. Allunga gastrocnemio e soleo.",
    },
    {
        "nome": "Stretching Pettorali alla Porta",
        "nome_en": "Doorway Chest Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["chest"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Avambracci su stipite, fare un passo avanti. Allunga pettorale maggiore e minore, deltoide anteriore.",
    },
    {
        "nome": "Stretching Dorsali (Child's Pose)",
        "nome_en": "Child's Pose Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["lats", "back"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Da ginocchia, sedere sui talloni e distendere le braccia avanti. Allunga dorsali, erettori spinali e spalle.",
    },
    {
        "nome": "Stretching Spalle (Cross-Body)",
        "nome_en": "Cross-Body Shoulder Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["shoulders"],
        "muscoli_secondari": ["traps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Braccio disteso davanti al petto, tirare con l'altro braccio. Allunga deltoide posteriore e romboidi.",
    },
    {
        "nome": "Stretching Tricipiti",
        "nome_en": "Overhead Tricep Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["triceps"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Braccio sopra la testa, gomito piegato, tirare con l'altra mano. Allunga capo lungo del tricipite.",
    },
    {
        "nome": "Stretching Adduttori (Farfalla)",
        "nome_en": "Butterfly Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["adductors"],
        "muscoli_secondari": ["glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Seduti, piante dei piedi unite, ginocchia verso il basso. Allunga adduttori e interno coscia.",
    },
    {
        "nome": "Stretching Glutei (Piriforme)",
        "nome_en": "Piriformis Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["glutes"],
        "muscoli_secondari": ["hamstrings"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Sdraiati, caviglia su ginocchio opposto, tirare la gamba verso il petto. Allunga piriforme e glutei.",
    },
    {
        "nome": "Stretching Flessori Anca",
        "nome_en": "Hip Flexor Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["quadriceps"],
        "muscoli_secondari": ["core", "glutes"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Affondo basso con ginocchio a terra, spingere il bacino avanti. Allunga ileopsoas e retto femorale.",
    },
    {
        "nome": "Stretching Schiena (Cat-Cow)",
        "nome_en": "Cat-Cow Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Da quadrupedia, alternare inarcamento e arrotondamento della schiena. Mobilizza tutta la colonna vertebrale.",
    },
    {
        "nome": "Stretching Collo Laterale",
        "nome_en": "Lateral Neck Stretch",
        "categoria": "stretching",
        "pattern_movimento": "stretch",
        "force_type": "static",
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["traps"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Inclinare la testa lateralmente, mano sulla tempia per assistere. Allunga trapezio superiore e scaleni.",
    },

    # ═══════════════════════════════════════════════════════════
    # MOBILITA — 12 esercizi
    # ═══════════════════════════════════════════════════════════
    {
        "nome": "Cerchi d'Anca",
        "nome_en": "Hip Circles",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["core", "quadriceps"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Rotazione completa dell'anca in entrambe le direzioni. Migliora ROM articolare coxo-femorale.",
    },
    {
        "nome": "Mobilita Caviglie",
        "nome_en": "Ankle Mobility Drill",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "unilateral",
        "muscoli_primari": ["calves"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Ginocchio avanti oltre la punta del piede, tallone a terra. Migliora dorsi-flessione tibiotarsica.",
    },
    {
        "nome": "Shoulder Dislocates (Bastone)",
        "nome_en": "Shoulder Dislocates",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["shoulders"],
        "muscoli_secondari": ["chest", "lats"],
        "attrezzatura": "barbell",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Con bastone impugnato largo, portare le braccia sopra la testa e dietro la schiena. Mobilizza cuffia dei rotatori.",
    },
    {
        "nome": "Rotazioni Toraciche",
        "nome_en": "Thoracic Spine Rotations",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "core"],
        "muscoli_secondari": ["shoulders"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Da quadrupedia o seduti, ruotare il torace aprendo il braccio. Migliora mobilita colonna toracica.",
    },
    {
        "nome": "90/90 Anca",
        "nome_en": "90/90 Hip Switch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["glutes", "adductors"],
        "muscoli_secondari": ["hamstrings", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Seduti a terra, entrambe le gambe piegate a 90 gradi, alternare lato. Mobilita rotazione interna/esterna anca.",
    },
    {
        "nome": "World's Greatest Stretch",
        "nome_en": "World's Greatest Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["quadriceps", "hamstrings", "back"],
        "muscoli_secondari": ["shoulders", "glutes", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Affondo profondo con rotazione toracica e braccio verso il cielo. Mobilita anca, torace e spalle in un movimento.",
    },
    {
        "nome": "Squat to Stand",
        "nome_en": "Squat to Stand",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["hamstrings", "quadriceps", "glutes"],
        "muscoli_secondari": ["back", "calves"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Dalla posizione eretta, toccare le punte dei piedi, poi scendere in squat profondo e risalire. Mobilita catena posteriore.",
    },
    {
        "nome": "Mobilita Polsi",
        "nome_en": "Wrist Mobility Drill",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["forearms"],
        "muscoli_secondari": [],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Rotazioni, flessioni e estensioni dei polsi in varie angolazioni. Prepara per esercizi di presa e push.",
    },
    {
        "nome": "Scorpion Stretch",
        "nome_en": "Scorpion Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["back", "glutes", "quadriceps"],
        "muscoli_secondari": ["shoulders", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Proni, portare il piede verso la mano opposta ruotando il bacino. Mobilita colonna lombare e flessori dell'anca.",
    },
    {
        "nome": "Open Book",
        "nome_en": "Open Book Rotation",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["back", "chest"],
        "muscoli_secondari": ["shoulders", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "beginner",
        "ore_recupero": 12,
        "descrizione_anatomica": "Sdraiati su un fianco, ruotare il braccio superiore aprendo il torace. Eccellente per mobilita toracica.",
    },
    {
        "nome": "Deep Squat Hold",
        "nome_en": "Deep Squat Hold",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": "static",
        "lateral_pattern": "bilateral",
        "muscoli_primari": ["quadriceps", "glutes", "adductors"],
        "muscoli_secondari": ["calves", "core", "back"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Mantenere posizione di squat profondo con talloni a terra. Migliora mobilita anche, caviglie e colonna.",
    },
    {
        "nome": "Spiderman Stretch",
        "nome_en": "Spiderman Stretch",
        "categoria": "mobilita",
        "pattern_movimento": "mobility",
        "force_type": None,
        "lateral_pattern": "alternating",
        "muscoli_primari": ["quadriceps", "glutes", "adductors"],
        "muscoli_secondari": ["hamstrings", "core"],
        "attrezzatura": "bodyweight",
        "difficolta": "intermediate",
        "ore_recupero": 12,
        "descrizione_anatomica": "Da posizione plank, portare il piede accanto alla mano. Mobilita flessori anca, adduttori e torace.",
    },
]


def seed_exercises():
    """Inserisce esercizi complementari se non esistono gia'."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    now = datetime.now().isoformat()
    inserted = 0
    skipped = 0

    for ex in EXERCISES:
        # Check se esiste gia' per nome (case-insensitive)
        cursor.execute("SELECT id FROM esercizi WHERE LOWER(nome) = LOWER(?)", (ex["nome"],))
        if cursor.fetchone():
            skipped += 1
            continue

        cursor.execute(
            """INSERT INTO esercizi (
                trainer_id, nome, nome_en, categoria, pattern_movimento,
                force_type, lateral_pattern,
                muscoli_primari, muscoli_secondari,
                attrezzatura, difficolta, ore_recupero,
                descrizione_anatomica, is_builtin, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                None,  # trainer_id NULL = builtin
                ex["nome"],
                ex["nome_en"],
                ex["categoria"],
                ex["pattern_movimento"],
                ex.get("force_type"),
                ex.get("lateral_pattern"),
                json.dumps(ex["muscoli_primari"]),
                json.dumps(ex.get("muscoli_secondari") or []),
                ex["attrezzatura"],
                ex["difficolta"],
                ex.get("ore_recupero", 12),
                ex.get("descrizione_anatomica"),
                1,  # is_builtin
                now,
            ),
        )
        inserted += 1

    conn.commit()
    conn.close()
    print(f"Seed completato su {DB_PATH}: {inserted} inseriti, {skipped} gia' esistenti.")


if __name__ == "__main__":
    seed_exercises()
